// <auto-generated />
using System;
using EmeraldChameleonChat.Services.DAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmeraldChameleonChat.Services.Migrations
{
    [DbContext(typeof(EmeraldChameleonChatContext))]
    partial class EmeraldChameleonChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()



                        .IsRequired()

                    b.Property<DateTime>("LastConnection")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()




                        .IsRequired()


                    b.HasKey("Id");

                });

            modelBuilder.Entity("EmeraldChameleonChat.Services.Model.Entity.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(250)

                    b.Property<double>("TemperatureC")

                    b.HasKey("Id");

                    b.ToTable("WeatherForecast");
                });
#pragma warning restore 612, 618
        }
    }
}
